spring:
  config:
    import: "optional:file:.env[.properties]"

  application:
    name: beyond-chat

    security:
      jwt:
        secret-key: ${KEY_256bit}
        expiration: 86400000      # 24 hours in miliseconds

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enable: true
      client-type: lettuce

  datasource:
    url: ${SQL_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE

brevo:
  api:
    key: ${BREVO_API}
